/**
 * MurmurHash3 (32-bit) implementation
 * Adapted for JavaScript
 */

function mul32(m, n) {
    var nlo = n & 0xffff;
    var nhi = n >>> 16;
    return ((m & 0xffff) * nlo) + ((((m >>> 16) * nlo + (m & 0xffff) * nhi) & 0xffff) << 16);
  }
  
  function murmurhash3_32_gc(key, seed) {
    var remainder, bytes, h1, h1b, c1, c1b, c2, c2b, k1, i;
    
    key = key || '';
    seed = seed || 0;
    
    remainder = key.length & 3; // key.length % 4
    bytes = key.length - remainder;
    h1 = seed;
    c1 = 0xcc9e2d51;
    c2 = 0x1b873593;
    i = 0;
    
    while (i < bytes) {
        k1 = 
          ((key.charCodeAt(i) & 0xff)) |
          ((key.charCodeAt(++i) & 0xff) << 8) |
          ((key.charCodeAt(++i) & 0xff) << 16) |
          ((key.charCodeAt(++i) & 0xff) << 24);
        ++i;
        
        k1 = mul32(k1, c1);
        k1 = ((k1 & 0x1ffff) << 15) | (k1 >>> 17);
        k1 = mul32(k1, c2);
        
        h1 ^= k1;
        h1 = ((h1 & 0x7ffff) << 13) | (h1 >>> 19);
        h1 = (h1 * 5 + 0xe6546b64) | 0;
    }
    
    k1 = 0;
    
    switch (remainder) {
        case 3: k1 ^= (key.charCodeAt(i + 2) & 0xff) << 16;
        case 2: k1 ^= (key.charCodeAt(i + 1) & 0xff) << 8;
        case 1: k1 ^= (key.charCodeAt(i) & 0xff);
        
        k1 = mul32(k1, c1);
        k1 = ((k1 & 0x1ffff) << 15) | (k1 >>> 17);
        k1 = mul32(k1, c2);
        h1 ^= k1;
    }
    
    h1 ^= key.length;
    
    h1 ^= h1 >>> 16;
    h1 = mul32(h1, 0x85ebca6b);
    h1 ^= h1 >>> 13;
    h1 = mul32(h1, 0xc2b2ae35);
    h1 ^= h1 >>> 16;
    
    return h1 >>> 0;
  }
  
  // Tachiyomi Source ID is a 64-bit integer, usually generated via MurmurHash2 or 3.
  // BUT: Extensions typically use the lower 64 bits? standard java hashCode() is 32-bit.
  // Let's assume Tachiyomi uses 64-bit hash. 
  // Wait, `kotlin.hashCode().toLong()` is 32-bit promoted to 64-bit.
  // Standard Injekt/SourceFactory uses: `id = name.hashCode().toLong()`?
  // NO. "The ID of the source is a 64-bit number generated by a hash function."
  // Most legacy sources use strict IDs.
  // GENERIC sources: `key.hashCode()` which is 32-bit int.
  
  /**
   * Generates a deterministic ID for a source name/lang combo.
   * Matches Tachiyomi's behavior for unknown sources?
   * Tachiyomi often uses: (name + " " + lang).hashCode()
   */
  function generateSourceId(name, lang = 'en') {
      const key = `${name.toLowerCase()} ${lang}`;
      // Basic 32-bit Java hash code simulation
      let hash = 0;
      for (let i = 0; i < key.length; i++) {
          const char = key.charCodeAt(i);
          hash = ((hash << 5) - hash) + char;
          hash = hash | 0; // Convert to 32bit integer
      }
      return String(hash); 
  }
  
  if (typeof window !== 'undefined') {
      window.generateSourceId = generateSourceId;
  }
